crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    
    path('admin/', admin.site.urls),

    path('', include('webapp.urls')),
]

webapp/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name=""),

    path('register', views.register, name="register"),

    path('my-login', views.my_login, name="my-login"),

    path('user-logout', views.user_logout, name="user-logout"),
    

    # CRUD

    path('dashboard', views.dashboard, name="dashboard"),

    path('create-record', views.create_record, name="create-record"),

    path('update-record/<int:pk>', views.update_record, name='update-record'),

    path('record/<int:pk>', views.singular_record, name="record"),

    path('delete-record/<int:pk>', views.delete_record, name="delete-record"),

   # path('record/', views.load_rolenames, name="record"),
    
   # path('ajax/load-rolenames/', views.load_rolenames, name='ajax-load-rolenames'), # AJAX
    
    path('load_rolenames/', views.load_rolenames, name='load_rolenames'), # AJAX
    


]

webapp/models.py
from django.db import models
# from multiselectfield import MultiSelectField
from django.contrib.auth.models import User

class Functionalarea(models.Model):
      name=models.CharField(max_length=500)

      def __str__(self):
         return self.name

class Rolename(models.Model):
    functionalarea=models.ForeignKey(Functionalarea, on_delete=models.CASCADE)
    name=models.CharField(max_length=500)
    def __str__(self):
         return self.name



class Record(models.Model):
    yesno_choice=[
        ("Yes", "Yes"),
        ("No", "No")
    ]

    registration_type=[
        ("Profit", "Profit"),
        ("Non Profit", "Non Profit")
    ]
    entry_level=[
        ("National", "National"),
        ("County", "County")
    ]
    partner_category=[
        ("Implementing", "Implementing"),
        ("Contracted", "Contracted"),
        ("Funder", "Funder")
    ]

    partnership_framework=[
        ("MOU", "National"),
        ("Implementation Letter", "Implementation Letter"),
        ("Letter of Intent", "Letter of Intent"),
        ("Partnership Agreement", "Partnership Agreement"),
        ("Implementation Letter", "Implementation Letter"),
        ("Contract", "Contract"),
        ("Other", "Other")
    ]

    county_choice=(
       ("All Counties", "All Counties"),
       ("Nairobi", "Nairobi"),
       ("Mombasa", "Mombasa"),
        ("Nakuru", "Nakuru")
    )

    entry_level=[
        ("National", "National"),
        ("County", "County")
    ]
   
   
    creation_date = models.DateTimeField(auto_now_add=True)
    stakeholder_name = models.CharField(max_length=100, blank=False, null=True)
    physical_location=models.TextField(blank=False, null=True)
    Primary_contact_tel=models.CharField(max_length=200, blank=False, null=True)
    year_of_registration=models.DateTimeField(blank=False, null=True)
    partner_category=models.CharField(choices=partner_category, null=True, blank=False)
    stakeholder_type = models.CharField(max_length=100, null=True, blank=False)
    # county = MultiSelectField(choices=county_choice, max_length=500)
    county = models.CharField(max_length=300, null=True, blank=False) 
    functionalarea = models.ForeignKey(Functionalarea, on_delete=models.SET_NULL, blank=False, null=True)
    rolename = models.ForeignKey(Rolename, on_delete=models.SET_NULL, blank=False, null=True)
    registration_type=models.CharField(choices=registration_type, null=True, blank=False)
    entry_level=models.CharField(choices=entry_level, null=True, blank=False)
    budget=models.CharField(max_length=200, null=True, blank=True)
    partnership_framework=models.CharField(choices=partnership_framework, null=True, blank=False)
    # hiv = models.CharField(choices=yesno_choice, null=True, blank=False)
    # malaria = models.CharField(choices=yesno_choice, null=True, blank=False)
    # fp = models.CharField(choices=yesno_choice, null=True, blank=False)
    # mnch = models.CharField(choices=yesno_choice, null=True, blank=False)
    # emms = models.CharField(choices=yesno_choice, null=True, blank=False)
    # emms = models.CharField(max_length=125)
    contact_email = models.CharField(max_length=125)
    notes = models.TextField(max_length=500)
    activity_reference = models.CharField(max_length=150)

    user = models.ForeignKey(User, on_delete=models.CASCADE)

# class countym(models.Model):
#     county = models.CharField(max_length=30)

# class Recordm(models.Model):
#     county = models.CharField(max_length=50)
#     counties = models.ManyToManyField(countym)

#     def __str__(self):
#         return "%s (%s)" % (
#             self.name,
#             ", ".join(counties.name for counties in self.counties.all()),
#         )

    def __str__(self):

        return self.stakeholder_name + "   " + self.stakeholder_type

webapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Record, Functionalarea, Rolename

from django import forms

from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput

from .models import models


class DateInput(forms.DateInput):
    input_type = 'date'

# - Register/Create a user

class CreateUserForm(UserCreationForm):

    class Meta:

        model = User
        fields = ['username', 'password1', 'password2']


# - Login a user

class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=TextInput())
    password = forms.CharField(widget=PasswordInput())


# - Create a record

class CreateRecordForm(forms.ModelForm):

    class Meta:

        model = Record 
        fields = ['stakeholder_name', 'physical_location', 'Primary_contact_tel', 
                  'year_of_registration', 'partner_category', 'stakeholder_type', 
                  'county', 'functionalarea', 'rolename', 'registration_type','entry_level','budget', 'partnership_framework',  
                  'contact_email', 'notes', 'activity_reference']
        widgets = {
            'year_of_registration': DateInput(),
        }
        # fields = ['stakeholder_name', 'stakeholder_type', 'county', 'functionalarea', 'rolename', 'hiv', 'malaria', 'fp', 'mnch', 'emms', 'contact_email', 'notes', 'activity_reference']
   
    functionalarea = forms.ModelChoiceField(queryset=Functionalarea.objects.all(),
        widget=forms.Select(attrs={"hx-get": "load_rolenames/", "hx-target": "#id_rolename"}))
    widgets = {
            'county': forms.SelectMultiple(attrs={'class': 'form-control'}),  # Render as a select dropdown with multiple selections
        }
    rolename = forms.ModelChoiceField(queryset=Rolename.objects.none())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if "functionalarea" in self.data:
            functionalarea_id = int(self.data.get("functionalarea"))
            self.fields["rolename"].queryset = Rolename.objects.filter(functionalarea_id=functionalarea_id)
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['rolename'].queryset = Rolename.objects.none()
 
    #     if 'functionalarea' in self.data:
    #         try:
    #             functionalarea_id = int(self.data.get('functionalarea'))
    #             self.fields['rolename'].queryset = Rolename.objects.filter(functionalarea_id=functionalarea_id).order_by('name')
    #         except (ValueError, TypeError):
    #             pass  # invalid input from the client; ignore and fallback to empty rolename queryset
    #     elif self.instance.pk:
    #         self.fields['rolename'].queryset = self.instance.functionalarea.rolename_set.order_by('name') 

#  for James

#     functionalarea = forms.ModelChoiceField(queryset=Functionalarea.objects.all(),
#         widget=forms.Select(attrs={"hx-get": "record/", "hx-target": "#id_rolename"}))
#     rolename = forms.ModelChoiceField(queryset=Rolename.objects.none())

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)

#         if "functionalarea" in self.data:
#             functionalarea_id = int(self.data.get("functionalarea"))
#             self.fields["rolename"].queryset = Rolename.objects.filter(functionalarea_id=functionalarea_id)



#for Paul

             
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['rolename'].queryset = Rolename.objects.none()
 
    #     if 'functionalarea' in self.data:
    #         try:
    #             functionalarea_id = int(self.data.get('functionalarea'))
    #             self.fields['rolename'].queryset = Rolename.objects.filter(functionalarea_id=functionalarea_id).order_by('name')
    #         except (ValueError, TypeError):
    #             pass  # invalid input from the client; ignore and fallback to empty rolename queryset
    #     elif self.instance.pk:
    #         self.fields['rolename'].queryset = self.instance.functionalarea.rolename_set.order_by('name')


# - Update a record

class UpdateRecordForm(forms.ModelForm):

    class Meta:

        model = Record
        fields = ['stakeholder_name', 'physical_location', 'Primary_contact_tel', 
                  'year_of_registration', 'partner_category', 'stakeholder_type', 
                  'county', 'functionalarea', 'rolename', 'registration_type','entry_level','budget', 'partnership_framework',  
                  'contact_email', 'notes', 'activity_reference']
        widgets = {
            'year_of_registration': DateInput(),
        }
        # fields = ['stakeholder_name', 'stakeholder_type', 'county', 'functionalarea', 'rolename', 'hiv', 'malaria', 'fp', 'mnch', 'emms', 'contact_email', 'notes', 'activity_reference']



class cascadeForm(forms.Form):
    functionalarea = forms.ModelChoiceField(queryset=Functionalarea.objects.all(),
        widget=forms.Select(attrs={"hx-get": "load_rolenames/", "hx-target": "#id_rolename"}))
    rolename = forms.ModelChoiceField(queryset=Rolename.objects.none())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if "functionalarea" in self.data:
            functionalarea_id = int(self.data.get("functionalarea"))
            self.fields["rolename"].queryset = Rolename.objects.filter(functionalarea_id=functionalarea_id)

webapp/views.py
from django.shortcuts import render, redirect
from .forms import CreateUserForm, LoginForm, CreateRecordForm, UpdateRecordForm, cascadeForm

from django.contrib.auth.models import auth
from django.contrib.auth import authenticate

from django.contrib.auth.decorators import login_required

from .models import Record, Functionalarea, Rolename

from django.http import HttpResponseForbidden, HttpResponseServerError

from django.contrib import messages
from django import forms

from django.http.response import JsonResponse



# - Homepage 

def home(request):

    return render(request, 'index.html')


# - Register a user

def register(request):

    form = CreateUserForm()

    if request.method == "POST":

        form = CreateUserForm(request.POST)

        if form.is_valid():

            form.save()

            messages.success(request, "Account created successfully!")

            return redirect("my-login")

    context = {'form':form}

    return render(request, 'webapp/register.html', context=context)


# - Login a user

def my_login(request):

    form = LoginForm()

    if request.method == "POST":

        form = LoginForm(request, data=request.POST)

        if form.is_valid():

            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:

                auth.login(request, user)

                return redirect("dashboard")

    context = {'form':form}

    return render(request, 'webapp/my-login.html', context=context)


# - Dashboard

@login_required(login_url='my-login')
def dashboard(request):

    my_records = Record.objects.all()
  
    context = {'records': my_records}

    return render(request, 'webapp/dashboard.html', context=context)


# - Create a record 

@login_required(login_url='my-login')
def create_record(request):

    form = CreateRecordForm()

    if request.method == "POST":
       

        form = CreateRecordForm(request.POST)

        if form.is_valid():
         
            record=form.save(commit=False)
            selected_counties = request.POST.getlist('county')
            counties_all=",".join(selected_counties)
          
            # counties=form.cleaned_data.get('county')
            # record.county=','.join(counties)
            # record.save()
            record.user=request.user
            record.county=counties_all

            record.save()

            messages.success(request, "Your record was created!")

            return redirect("dashboard")

    context = {'form': form}
 

    return render(request, 'webapp/create-record.html',context)


# - Update a record 

@login_required(login_url='my-login')
def update_record(request, pk):


    # def dispatch(self, request, *args, **kwargs):
    #     handler = super(login_required, self).dispatch(request, *args, **kwargs)
    #     # Only allow editing if current user is owner
    #     if self.object.author != request.user:
    #         return HttpResponseForbidden(u'You can only edit records created by you!.')
    #     return handler

    # def get_success_url(self):
    #     return redirect('dashboard', args=[self.object.pk])
    
    record = Record.objects.get(id=pk)

    form = UpdateRecordForm(instance=record)




    if request.method == 'POST':
    

        form = UpdateRecordForm(request.POST, instance=record)

        if form.is_valid():

            form.save()

            messages.success(request, "Your record was updated!")

            return redirect("dashboard")
        
    context = {'form':form}

    return render(request, 'webapp/update-record.html', context=context)


# - Read / View a singular record

@login_required(login_url='my-login')
def singular_record(request, pk):

    all_records = Record.objects.get(id=pk)
    is_owner = all_records.user == request.user

    context = {'record':all_records,'is_owner': is_owner}

    return render(request, 'webapp/view-record.html', context=context)


# - Delete a record

@login_required(login_url='my-login')
def delete_record(request, pk):

    record = Record.objects.get(id=pk)

    record.delete()

    messages.success(request, "Your record was deleted!")

    return redirect("dashboard")



# - User logout

def user_logout(request):

    auth.logout(request)

    messages.success(request, "Logout success!")

    return redirect("my-login")

def index(request):
     form=cascadeForm()
     return render(request, 'webapp/index.html', {"form1": form})

def load_rolenames(request):
    functionalarea_id = request.GET.get("functionalarea")
    rolenames = Rolename.objects.filter(functionalarea_id=functionalarea_id)
    return render(request, 'webapp/rolename_dropdown.html', {"rolenames": rolenames})





# # AJAX
# def load_rolenames(request):
#     Functionalarea_id = request.GET.get('Functionalarea_id')
#     rolenames = Rolename.objects.filter(Functionalarea_id=Functionalarea_id).all()
#     return render(request, 'webapp/rolename_dropdown_list_options.html', {'rolenames': rolenames})
    # print({'rolenames': rolenames})
    # return JsonResponse(list(rolenames.values('id', 'name')), safe=False)


#for J
# def load_rolenames(request):
#     functionalarea_id = request.GET.get("functionalarea")
#     rolenames = Rolename.objects.filter(functionalarea_id=functionalarea_id)
#     return render(request, "create-record.html", {"rolenames": rolenames})

# without Jquery
# def load_rolenames(request):
#     functionalarea_id = request.GET.get("functionalarea")
#     rolenames = Rolename.objects.filter(functionalarea_id=functionalarea_id)
#     return render(request, "webapp/rolename_dropdown_list_options.html", {"rolenames": rolenames})

webapp/templates/webapp/base.html
{% load static %}

<!DOCTYPE html>

<html>

    <head> 

        <meta charset="utf-8">

        <meta name="viewport" content="width=device-width, initial-scale=1">


        <title> Stakeholder Mapping </title>

        <!-- <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/minty/bootstrap.min.css"> -->
        <link rel="stylesheet" type="text/css" href="https://bootswatch.com/5/flatly/bootstrap.min.css">

        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css" />
        <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.0.5/css/buttons.dataTables.min.css">

    </head>

    <body>

        <!-- Create Navbar here -->

        {% include 'webapp/navbar.html' %}

        <div class="container">

            <br>

            <!-- Notification messages -->

            {% for message in messages %}

                {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}


                    <p id="message-timer" class="alert alert-success float-center text-center message-text"> 

                        <i class="fa fa-check" aria-hidden="true"></i> &nbsp; {{message}}

                    </p>


                {% endif %}


            {% endfor %}


           {% block content %}




           {% endblock %}


        </div>

        <script src="{% static 'js/app.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
        <script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script>
        <script src="https://cdn.datatables.net/buttons/3.0.2/js/dataTables.buttons.js"></script>
        <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.dataTables.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>
        <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.html5.min.js"></script>
        <script src="https://cdn.datatables.net/buttons/3.0.2/js/buttons.print.min.js"></script>
<!-- 
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script> -->
      

        <!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script> -->
        
        
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script>

            $(document).ready(function() {
                $('#stakeholder').DataTable({
                    layout: {
                        topStart: {
                     buttons: ['copy', 'csv', 'excel', 'print']
                    //buttons: ['copy', 'csv', 'excel', 'pdf', 'print']
                      }
                    },
                    
                });
            });
            </script>

    </body>



</html>

webapp/templates/webapp/create-record.html
{% extends 'webapp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<script src="https://unpkg.com/htmx.org@1.9.2"></script>

<!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" /> -->
    <body>

        <div class="container bg-light shadow-md p-5 form-layout">

            <h3> Create record </h3>

            <h6> Start adding in the required details for your record. </h6>

            <hr>
            <br>

            <form method="POST" autocomplete="off" id="createRecord">

                {% csrf_token %}
           
                {{form.stakeholder_name|as_crispy_field}}
                <br>
                <hr>
                {{form.physical_location|as_crispy_field}}
                <br>
                <hr>
                {{form.Primary_contact_tel|as_crispy_field}}
                <br>
                <hr>
                {{form.year_of_registration|as_crispy_field}}
                <br>
                <hr>
                {{form.partner_category|as_crispy_field}}
               
                <br>
                <hr>
                {{form.stakeholder_type|as_crispy_field}}

                <br>
                <hr>
                 
                 <br>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/css/bootstrap-select.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.8.1/js/bootstrap-select.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script> 

<select name="county" class="selectpicker" multiple data-live-search="true" id="county" aria-multiselectable="true" aria-multiline="true">
  <option>Mombasa</option>
  <option>Nairobi</option>
  <option>Kisumu</option>
</select>


<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js"></script>

<select class="select_field_class" multiple="multiple" name="county" id="county">
      <option value="">Enter the option</option>
      {% for option in options %}
         <option value="{{ option.id }}">{{ option.name }}</option>
      {% endfor %}
</select> -->

<!-- $('.select_field_class').select2( { placeholder: "Select here", maximumSelectionSize: 100  } ); -->




                <br>
                <hr>
                {{form.functionalarea|as_crispy_field}}

                <br>
                <hr>
                {{form.rolename|as_crispy_field}}
                <br>
                <hr>
                {{form.registration_type|as_crispy_field}}
                <br>
                <hr>
                {{form.entry_level|as_crispy_field}}
                <br>
                <hr>
                {{form.budget|as_crispy_field}}
                <br>
                <hr>
                {{form.partnership_framework|as_crispy_field}}


                <br>
                <!-- <label>HIV</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="hiv" id="inlineRadio1" value="Yes">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="hiv" id="inlineRadio2" value="No">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                  </div>                 -->


                <br>
                <!-- <label>Malaria</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="malaria" id="inlineRadio1" value="Yes">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="malaria" id="inlineRadio2" value="No">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                  </div> -->


           
                <!-- <label>FP</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="fp" id="inlineRadio1" value="Yes">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="fp" id="inlineRadio2" value="No">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                  </div>                 -->
           

      
                <!-- <label>MNCH</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="mnch" id="inlineRadio1" value="Yes">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="mnch" id="inlineRadio2" value="No">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                  </div> -->
                 
          

        
                <!-- <label>EMMS</label>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="emms" id="inlineRadio1" value="Yes">
                    <label class="form-check-label" for="inlineRadio1">Yes</label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="emms" id="inlineRadio2" value="No">
                    <label class="form-check-label" for="inlineRadio2">No</label>
                  </div> -->
   
                              <hr>
                {{form.contact_email|as_crispy_field}}

                <br>
                <hr>
                {{form.notes|as_crispy_field}}

                <br>
                <hr>
                {{form.activity_reference|as_crispy_field}}
                <hr>
                <br>
          
                <button type="submit" class="btn btn-primary"> 
                    
                    Create record &nbsp; <i class="fa fa-check" aria-hidden="true"></i>

                </button>

                &nbsp;

                <a href="{% url 'dashboard' %}" class="btn btn-secondary"> 


                    Return &nbsp; <i class="fa fa-arrow-left" aria-hidden="true"></i>

                </a>
                <!-- Include jQuery and Select2 JS -->
               

            </form>


        </div>

        <br>
        
      
        <!-- <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script> 
        <script>$("#btnLeft").click(function () {
          var selectedItem = $("#rightValues option:selected");
          $("#leftValues").append(selectedItem);
      });
      
      $("#btnRight").click(function () {
          var selectedItem = $("#leftValues option:selected");
          $("#rightValues").append(selectedItem);
      });
      
      $("#rightValues").change(function () {
          var selectedItem = $("#rightValues option:selected");
          $("#txtRight").val(selectedItem.text());
      });</script> -->
        <!-- <script>
            $("#id_functionalarea").change(function () {
                const url = $("#createRecord").attr("data_rolenames_url");  // get the url of the role names
                const functionalareaId = $(this).val();  // get the selected functionalarea ID from the HTML input
         
                $.ajax({                       // initialize an AJAX request
                    url: url,                    // set the url of the request (= /members/ajax/load-cities/ )
                    data: {
                        'functionalarea_id': functionalareaId       // GET parameters
                    },
                    success: function (data) {   
                        console.log(data)
                        $("#id_rolename").html(data); 
                    }
                });
         
            });
        </script> --> 

    </body>

{% endblock %}

webapp/templates/webapp/dashboard.html
{% extends 'webapp/base.html' %}

{% block content %}
<!-- <link rel="stylesheet" href="https://cdn.datatables.net/2.0.5/css/dataTables.dataTables.css" />
  
<script src="https://cdn.datatables.net/2.0.5/js/dataTables.js"></script> -->

    <h5> Welcome, {{user}}! 👋 </h5>

    <hr>

    <a class="btn btn-outline-primary btn-sm" href="{% url 'create-record' %}">

        Create a new record &nbsp; <i class="fa fa-plus-circle" aria-hidden="true"></i>

    </a>

    <hr> 

    <table class="table table-hover table-bordered" id="stakeholder">

        <thead class="table-light">

            <tr>

                <th scope="col"> ID </th>
                <th scope="col"> Stakeholder Name </th>
                <th scope="col"> stakeholder_type  </th>
                <th scope="col"> county  </th>
                <th scope="col"> Functional Area  </th>
                <th scope="col"> Role  </th>
                <th scope="col"> contact_email </th>
                <th scope="col"> notes </th>
                <th scope="col"> activity_reference </th>
                <th scope="col"> Date joined </th>
                <th scope="col"> View </th>
                
            </tr>

        </thead>

        <tbody>

        {% if records %}

            {% for record in records %}

            <tr>

                <td> {{record.id}} </td>
                <td> {{record.stakeholder_name}} </td> 
                <td> {{record.stakeholder_type}} </td>
                <td> {{record.county}} </td>
                <td> {{record.functionalarea}} </td>
                <td> {{record.rolename}} </td>
                <td> {{record.contact_email}} </td>
                <td> {{record.notes}} </td>
                <td> {{record.activity_reference}} </td>
                <td> {{record.creation_date}} </td>
               
                <td> 
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <a class="btn btn-success btn-sm" href="{% url 'record' record.id %}"> <i class="fa fa-eye" aria-hidden="true"></i> </a>
                        
                        </div>
                    </div>
                     </td>
                     

            </tr>

            {% endfor %}
        
        {% endif %}


        </tbody>


    </table>


{% endblock %}

webapp/templates/webapp/indexx.html
{% extends 'webapp/base.html' %}

{% block content %}
    
    <body>
         <form method="POST">
            {% crsf_token %}
            {{form.as_p}}
         </form>

    </body>        


{% endblock %}

webapp/templates/webapp/rolename_dropdown.html
{% for rolename in rolenames %}
<option value="{{ rolename.id }}">{{ rolename.name }}</option>
{% endfor %}